version: '3.1'

services:
  db:
    container_name: pizzastore
    image: postgres
    volumes:
      - pizzastore_db-data:/var/lib/postgresql/data
    ports:
      - 4444:5432
    environment:
      POSTGRES_USER: pizzastore
      POSTGRES_PASSWORD: pizzastore
      POSTGRES_DB: pizzastore
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - postgres_net
volumes:
  pizzastore_db-data:

networks:
  postgres_net: